### ISSUE TITLE
 'traverson-hal' is not in the npm registry.

### ISSUE THREAD

**Issue by Amadox** [basti1302/traverson-hal#2] opened 2015-02-27 10:43 UTC
$ npm install traverson-hal --save
npm WARN package.json testproject@0.0.0 No description
npm WARN package.json testproject@0.0.0 No repository field.
npm WARN package.json testproject@0.0.0 No README data
npm ERR! Linux 3.2.0-67-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "traverson-hal" "--save"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code E404

npm ERR! 404 Not Found: traverson-hal
npm ERR! 404
npm ERR! 404 'traverson-hal' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'testproject'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by basti1302** [comment] 2015-02-27 10:47
Yeah, right, it has not been released yet. I'm still working on the Traverson 1.0.0, which adds support for media type plug-ins. I might release today or in the next few days.

**Comment by Amadox** [comment] 2015-02-27 11:09
I noticed after opening the Issue. Am eager to try your stuff out, as it looks really awesome. Looking forward to the 1.0.0 release!

FYI, I grabbed your current master of traverson and traverson-hal, and tried out your example code with the haltalk API, just to play around a bit, and got the following console error:

XMLHttpRequest cannot load http://haltalk.herokuapp.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://angular-setup.ma.dev.25th-floor.com:81' is therefore not allowed access.

**Comment by basti1302** [comment] 2015-02-27 11:10
Thanks for the report, I'll have a look later.

**Comment by basti1302** [comment] 2015-02-27 20:06
traverson-hal 1.0.0 has been released via npm and bower.

I did not have a change to look into the haltalk issue but since this ticket was opened for traverson-hal not being on npm, I'll close this one now.

**Closed by basti1302** 2015-02-27 20:06 UTC

**Comment by dcerecedo** [comment] 2015-07-20 14:52
Using traverson-hal 2.0.0 (with traverson and traverson-angular) on localhost:9000 against an API on localhost:8080. The API is returning the following headers:

````
Access-Control-Allow-Headers → x-requested-with
Access-Control-Allow-Methods → POST, PUT, GET, OPTIONS, DELETE
Access-Control-Allow-Origin → *
Access-Control-Max-Age → 3600
Content-Type → application/hal+json;charset=UTF-8
Date → Mon, 20 Jul 2015 14:45:15 GMT
Server → Apache-Coyote/1.1
Transfer-Encoding → chunked
X-Application-Context → application:default:8080
````

But traverson says:

````
XMLHttpRequest cannot load http://localhost:8080/api. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.
````

Seems like a problem or maybe we are misusing traverson-hal.

**Comment by basti1302** [comment] 2015-07-20 16:54
I would guess that this is not a traverson or traverson-hal issue, but an issue with your CORS setup. Of course I might be wrong about that.

Could you make a simple test without all the traverson libraries? Perhaps just one simple ajax request from localhost:9000 to localhost:8080, either with JQuery or with plain vanilla XMLHttpRequest.

And please, do not add new questions to completely unrelated bug tickets. If you still think this issue is a bug in traverson-hal or traverson, by all means, open a new issue for it (ideally with some code to reproduce it).

**Comment by dcerecedo** [comment] 2015-07-21 08:07
Thaks @basti1302! and sorry for mixing up threads. I'll test your suggestion and let you know.
